{% set name = "oasis-deconv" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/j-friedrich/OASIS/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9ae6d77b034905c00d70a930b370de48b186dd2dd044556aeb99b6c59d0aa334

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - cython
    - pip
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - scipy
    - matplotlib-base

test:
  imports:
    - oasis
  # requires:
  #   - nose2
  #   - cvxpy  # [not (osx and py313)]
  #   - ecos   # [not (osx and py313)]
  # source_files:
  #   - tests
  # commands:
  #   - nose2 tests  # [not (osx and py313)]

about:
  home: https://github.com/j-friedrich/OASIS
  summary: Fast algorithm for deconvolution of neural calcium imaging traces
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-friedrich
