{% set name = "oasis-deconv" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/j-friedrich/OASIS/archive/refs/tags/v0.2.0.tar.gz
  sha256: 3be3de589b0d070e0e0af4f215b2a16d41389be9206e90720827cec66af602b1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - cython
    - pip
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - scipy
    - matplotlib-base
    - cython

test:
  imports:
    - oasis
  requires:
    - pytest
    - setuptools<=64.0.2
    - cvxpy
    - pip
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/j-friedrich/OASIS
  summary: Fast algorithm for deconvolution of neural calcium imaging traces
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-friedrich
