{% set name = "oasis-deconv" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/j-friedrich/OASIS/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bf8e13c289cd9e66eb44d2f9aae74401d4256ae22779d61d7f1fc3417dee5088

build:
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - hatchling
    - hatch-cython
    - cython
    - numpy
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - oasis
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/j-friedrich/OASIS
  summary: Fast algorithm for deconvolution of neural calcium imaging traces
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - j-friedrich
